// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frdsuyjyjissbeuzweef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZHN1eWp5amlzc2JldXp3ZWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTcxMjEsImV4cCI6MjA2NzczMzEyMX0.2limzNkuK6B-xgwfesefT0SQKKAc3s5MO4s1HezTeZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});